name: Test VyOS Docker Image

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # - name: Show installed packages
    #   run: | 
    #     sudo dpkg -l
    #     sudo python3 -V
    
    # - name: Install jq
    #   run: sudo apt-get update && sudo apt-get install -y jq

    - name: Build VyOS Docker Image
      run: ./build.sh
      # Ensure build.sh is executable: chmod +x build.sh in your repo

    - name: Check container image
      run: docker image ls

    - name: Start container
      run: docker run --rm -d --privileged -v /lib/modules:/lib/modules --name vyos-node1 vyos-container:latest /sbin/init

    - name: Check container
      run: docker ps

    # - name: Set up Python
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version: '3.x' # Use a recent Python 3 version

    - name: Install Robot Framework and dependencies
      run: |
        pip install robotframework
        pip install robotframework-SSHLibrary
        pip install robotframework-telnetlibrary

    - name: Run Robot Framework Tests
      run: |
        robot tests/test_vyos_container.robot
      # Ensure test_vyos_container.robot is in the root of your repo
